- README.rst
This seems like the right link?
> Fix PreTeXt link.

- bases/rsptx/interactives/runestone/mchoice/multiplechoice.py
I'm obviously not super familiar yet with this code or the output we're trying to create but this at least helps create valid XML when converting CSAwesome. I think it's right but I may have missed something.
> This fixes part of the CSAwesome conversion.

- bases/rsptx/interactives/runestone/common/runestonedirective.py
I'm not sure when this code runs because I'm not sure it ever caught a malformed ID, even when I'm pretty sure there were some. But anyway I mad this change when trying to catch some bad IDs and I'm pretty certain it's right even if it never fired and it does simplify the code a bit and shows how to do this kind of thing with a regexp.
> Validate xml:id just with regexp

- projects/jobe/files/CodeTestHelper.java
Kate's revision for handling static vars.
> Update CodeTestHelper again

- projects/jobe/files/CodeTestHelper.java
We added a new method to our CodeTestHelper. Haven't actually started using it obviously but once it's live we may.
> New version of CodeTestHelper.java

- projects/jobe/files/CodeTestHelper.java
This updates adds some new methods for expressing assertions a bit more easily.
> CodeTestHelper.java 3.1.0

- docs/source/developing.rst
**Issue:**
The 'Developing' page was a little unclear, and it was hard to find where to go next.
**Fix:** 
added changes to developing.rst file to make the changes, and added clarification that will help the reader understand what to do next.
**To test:**
Go to Developing page, and see the changes added.
> fix 399, add clarification

- bases/rsptx/interactives/runestone/dragndrop/dragndrop.py
- bases/rsptx/interactives/runestone/dragndrop/js/dragndrop.js
Attempted to add a randomize flag to drag and drop matching type questions.
> Possible Randomize Flag For Fixing Dropzone Column Order

- bases/rsptx/interactives/runestone/common/js/runestonebase.js
@bnmnetp, is this what you meant by checking for a runestone page to suppress the captions in PreText? I don't have a lot of experience coding in js, so please eyeball the syntax. Thanks.
> Update addCaption to suppress PreText captions in runestonebase.js

- docs/source/addbook.rst
> Fixed the typo in addbook.rst

- bases/rsptx/web2py_server/applications/runestone/controllers/assignments.py
- bases/rsptx/web2py_server/applications/runestone/views/assignments/practice.html
I also removed the request for feedback form. We haven't analyzed the contents of it, and it's pretty intrusive, so I thought it better to just remove it.
> Better phrasing throughout and especially for coursera_mode.

- bases/rsptx/interactives/runestone/poll/js/poll.js
This should also be more compatible with other PreTeXt questions where the query options may contain arbitrary html.
> Fix: properly render math in a poll question

- bases/rsptx/assignment_server_api/assignment_builder/.env.development
- bases/rsptx/assignment_server_api/assignment_builder/.env.production
- bases/rsptx/assignment_server_api/assignment_builder/src/App.jsx
- bases/rsptx/assignment_server_api/assignment_builder/src/navUtils.js
- bases/rsptx/assignment_server_api/assignment_builder/vite.config.js
- bases/rsptx/assignment_server_api/core.py
- bases/rsptx/assignment_server_api/routers/instructor.py
- components/rsptx/response_helpers/core.py
- components/rsptx/templates/_react_base.html
- components/rsptx/templates/assignment/instructor/builder.html
- components/rsptx/templates/common/static_assets_min.html
This makes accessing the react interface much more a part of the overall system.  And it adds a nifty navbar at the top as well.  More to come.
> Route changes

- bases/rsptx/interactives/webpack.config.js
- docs/source/javascript_feature.rst
Improves workflow for Runestone js development with PreTeXt books.
Goes with https://github.com/PreTeXtBook/pretext/pull/2197
> Components dev improvements

- bases/rsptx/interactives/runestone/timed/js/timed.js
- bases/rsptx/web2py_server/applications/runestone/controllers/admin.py
**Issue**
An instructor can create personalized quizzes and Timed Exams for students. When the students take the exam and click on the Finish Exam button, a message informing asking them if there are ready to submit their exam pops up. However, there is no indication that they have skipped questions, which can occur by mistake or by choice.
**Solution**
In that message, we can integrate the number of skipped questions so that the students are aware of the number of questions that are unfinished or they have not answered. In that case, if a student proceeds with the submission, it will be solely based on the student's will, not a minor mistake that pertains to the Runestone platform. We modified the message in the "timed.js" file, precisely inside the async function located inside the …
> Warning of Skipped Questions in Timed Exam

- bases/rsptx/interactives/runestone/parsons/js/parsons-i18n.en.js
- bases/rsptx/interactives/runestone/parsons/js/parsons.js
This goes with pretext PR: https://github.com/PreTeXtBook/pretext/pull/2204
I am fairly confident about RS side. PTX side may need some tweaks.
> Executable parsons

- bases/rsptx/web2py_server/applications/runestone/static/js/peer.js
- bases/rsptx/web2py_server/applications/runestone/views/peer/dashboard.html
I have reviewed the new interactivity + arrangement of buttons with Barb and she believes they're better than the existing design.
> Fix: Interactivity + placement of PI buttons

- projects/jobe/files/CodeTestHelper.java
@kmcdonnell2 added 2 new methods to CodeTestHelper.java for Java code with input.
> New methods in CodeTestHelper.java

- projects/jobe/Dockerfile
@bnmnetp If/when you merge could you update the RS server with doctest.h?
> Add doctest, remove catch precompilation

- bases/rsptx/interactives/ptxrs-bootstrap.less
- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/css/activecode.less
- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
- bases/rsptx/interactives/runestone/activecode/js/extractUnitResults.js
- bases/rsptx/interactives/runestone/clickableArea/css/clickable.css
- bases/rsptx/interactives/runestone/codelens/css/pytutor.css
- bases/rsptx/interactives/runestone/common/css/presenter_mode.less
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
- bases/rsptx/interactives/runestone/common/js/presenter_mode.js
- bases/rsptx/interactives/runestone/datafile/css/datafile.css
- bases/rsptx/interactives/runestone/dragndrop/css/dragndrop.css
- bases/rsptx/interactives/runestone/dragndrop/css/dragndrop.less
- bases/rsptx/interactives/runestone/fitb/css/fitb.css
- bases/rsptx/interactives/runestone/hparsons/css/hparsons.css
- bases/rsptx/interactives/runestone/parsons/css/parsons.css
- bases/rsptx/interactives/runestone/parsons/css/parsons.less
- bases/rsptx/interactives/runestone/parsons/css/prettify.css
- bases/rsptx/interactives/runestone/parsons/js/prettify.js
- bases/rsptx/interactives/runestone/tabbedStuff/css/tabbedstuff.css
- bases/rsptx/interactives/webpack.config.js
- bases/rsptx/interactives/webpack.index.js
This has styling updates to play well with the new PTX CSS. 
https://github.com/PreTeXtBook/pretext/pull/2291
Not needed to test out PTX, but without this RS components don't respect dark mode or do other adjustments based on PTX styling.
Should be safe to merge before PTX changes go live. Other than a rebase, I hadn't touched this since Sept... pretty sure it is stable.
> Css bundling help

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
Fix issue with overly long section delimeters in AC
> Allow for 5+ char long AC part delimeters

- bases/rsptx/assignment_server_api/assignment_builder/src/App.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AddExerciseModal.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercisesHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercisesHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ExercisePreview/ExercisePreviewModal.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SearchExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SearchExercisesHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/reading/AssignmentReadingsHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/hooks/useAddAssignmentExercise.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/hooks/useExerciseSearch.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/hooks/useExercisesSelector.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/hooks/useReadingsSelector.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/state/store.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/assignment/assignment.logic.api.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/chooseExercises/chooseExercises.logic.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/exercises/exercises.logic.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/readings/readings.logic.api.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/readings/readings.logic.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/rootReducer.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/store/searchExercises/searchExercises.logic.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/styles/_table.scss
- bases/rsptx/assignment_server_api/assignment_builder/src/styles/layout.scss
- bases/rsptx/assignment_server_api/assignment_builder/src/types/treeNode.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/utils/exercise.ts
@bnmnetp 
- The "Add Exercise" button is now sticky.
- All actions related to adding/removing readings/exercises now display a Toast message to make the process more user-friendly.
> RUN-21 Improve UX when adding/removing readings/exercises

- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
- bases/rsptx/interactives/runestone/shortanswer/css/shortanswer.css
Fix for dark mode issues with Short Answer and cpp codemirror.
> Improve short answer and codemirror in dark mode

- bases/rsptx/interactives/ptxrs-bootstrap.less
- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
- bases/rsptx/interactives/runestone/parsons/css/parsons.css
- bases/rsptx/interactives/runestone/parsons/css/parsons.less
- bases/rsptx/interactives/runestone/parsons/css/prettify.css
- bases/rsptx/interactives/runestone/parsons/js/parsons.js
Two unrelated set of fixes.
- First commit should prevent interactions between Parsons styling for prettify (non PTX environment) and Prism (PTX)
- Second has a few dark mode fixes
> Parsons syntax highlight update & dark mode fixes

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
I *think* this is what needs to be done to partially address #661, but testing is not working for me.  I can ask about how to better set up the javascript testing environment better at drop-in.
> add screen reader support for activecode

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
Changes sizing for CodeMirrors to be automatic based on height (up to limit based on viewport height).
> CodeMirror autosizing

- bases/rsptx/book_server_api/routers/rslogging.py
- bases/rsptx/interactives/runestone/codelens/css/pytutor.css
- bases/rsptx/interactives/runestone/codelens/js/codelens.js
- bases/rsptx/interactives/runestone/codelens/js/pytutor-embed.bundle.js
- components/rsptx/db/crud.py
Updates Codelen to handle questions with HTML controls. With each answered question a score update is sent with partial credit based on the number of questions answered during this session. 
Also allows for specifying starting step for the trace.
I tested this against a `Overview` RST build and it seems to work fine. Then tested against sample-book prior to any changes in it. Also seems fine. 
I *believe* it is fine to merge this prior to action on partner PR: https://github.com/PreTeXtBook/pretext/pull/2513
(It looks like question scoring was completely off for codelens based on a typo in `EVENT2TABLE`.)
> Codelens questions update

- components/rsptx/build_tools/core.py
Tested in process-manifest and build - both contexts successfully work.
I didn't add nest_asyncio to explicit dependencies in pyproject.toml files as we appear to be getting it indirectly and this isn't intended to stick around.
(Though the fact that we are getting it indirectly does mean that we are dependent on it... not sure if that makes your big fix more or less urgent.)
> Temporary patch: handle sync or async context in manifest_data_to_db

- bases/rsptx/interactives/runestone/activecode/js/activecode-i18n.en.js
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
Adds ctrl-s (Save & Run) and ctrl-/ (toggle comment on selection) keybindings to activecode editors.
> Activecode add bindings for ctrl-s and ctrl-/

- bases/rsptx/admin_server_api/routers/lti1p3.py
- components/rsptx/db/crud/crud.py
As discussed on discord - try to use LTI reported domain to verify authorization
> LTI1p3: Verify tool reported issuer domain not instructor provided domain

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ExercisePreview/ExercisePreview.tsx
Fix issue #756: Problem with preview mode in new assignment interface
> Fix issue #756

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/EditAllExercises/EditDropdownValueHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/ui/EditableTable/EditableTableDropdownCell.tsx
> Fix issue #758 - Show all the available options for autograde/which_to_grade

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.tsx
Fix issue #772: Creating a new assignment doesn't take you to the screen to edit it and add questions
> Fix issue #772

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercises.tsx
- components/rsptx/db/crud/question.py
> Fix issue 794 - Cannot uncheck chosen exercises and ordering

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/edit/AssignmentEdit.tsx
> Fix issue 860 - New Assignment Builder timed exam settings not saved

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercisesList/AssignmentExercisesTable.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CopyExercise/CopyExerciseModal.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CopyExercise/index.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SmartSearchExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/store/assignmentExercise/assignmentExercise.logic.api.ts
- bases/rsptx/assignment_server_api/routers/instructor.py
- components/rsptx/db/crud/question.py
- components/rsptx/validation/schemas.py
> Fix issue #791 - Add functionality to copy exercise

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/AssignmentBuilderCreate.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/AssignmentBuilderEdit.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/edit/AssignmentEdit.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/wizard/AssignmentWizard.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/defaultAssignment.ts
- bases/rsptx/assignment_server_api/routers/student.py
- components/rsptx/validation/schemas.py
Fix issue #812: Timed exam builder: allow 0 minutes for untimed and possibly rename to Timed to Quiz or Exam
> Fix issue #812

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercisesList/AssignmentExercisesTable.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/shared/BaseExerciseSettingsContent.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/config/exerciseTypes.ts
> Fix issue 806

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/shared/ExerciseLayout.tsx
> Fix issue 815 - Remove checkmark in Save when you create an exercise - make it clearer that you need to save

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercisesHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/store/assignmentExercise/assignmentExercise.logic.api.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/utils/exercise.ts
- components/rsptx/db/crud/assignment.py
> issue-878 - The number of points is wrong on an assignment / issue-818 - When browsing chapters for an exercise - allow a filter by type

- docs/source/database.rst
> fix environment variable typo

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/ActiveCodeExercise/ActiveCodeExercise.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/ParsonsExercise/ParsonsExercise.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/utils/tag.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SmartSearchExercises.tsx
- components/rsptx/db/crud/question.py
Fix #817. Add automatic programming language tag setting for creating activecode and parsonsprob exercises.
> Fix issue #817 - When searching for exercises - allow the user to limit by the programming language

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/MultiChoiceExercise.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/MultiChoiceOptions.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/MultiChoiceOptions.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/components/MultiChoiceOptionsWrapper.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/components/MultiChoiceOptionsWrapper.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/components/MultiChoiceQuestion.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/MultiChoiceExercise/components/StatementPreview.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/ParsonsExercise/components/ParsonsBlocksManager.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/components/ParsonsExercise/components/ParsonsExercise.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/shared/styles/CreateExercise.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/shared/styles/ExerciseStepWrapper.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/TipTap/Editor.module.css
Add statement preview to 2 step
Minimal supported screen width with 100% scaling is 1024px.
Anything lower than 1024px is going into 2 horizontal columns and not much usable.
Right now it is not possible to create a usable interface with lower resolution, if you have any ideas - tell me. 
https://github.com/user-attachments/assets/cefb646b-24cd-41d5-a63a-19c28245305b
> Mchoice enhancement

- docs/source/running.rst
I just tried running a rs server with docker compose and ran into a few gotchas.  I think the changes I made here are correct, but feel free to fix them if not.
> Clarify some steps in the docs for running a rs server

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/utils/exercise.ts
> Fix issue 856 - New Assignment Builder: filter out datafiles from Browse Chapter Exercises

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/CreateExercise/shared/styles/ExerciseStepWrapper.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/utils/preview/parsonsPreview.tsx
> Fix issue 900. The new assignment builder for Parsons problems messes up the block order.

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/AssignmentBuilderCreate.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/list/AssignmentList.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/defaultAssignment.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/types/assignment.ts
- bases/rsptx/assignment_server_api/routers/instructor.py
> issue-953 Add "released" toggle to main assignment builder page

- bases/rsptx/admin_server_api/routers/lti1p3.py
- bases/rsptx/web2py_server/applications/runestone/controllers/default.py
- components/rsptx/db/crud/user.py
This hopefully fixes the issue with using LTI1p3 links when instructor is impersonating a student in Canvas
> LTI1p3 improve anon user handling

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/AssignmentBuilderCreate.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/list/AssignmentList.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/defaultAssignment.ts
- bases/rsptx/assignment_server_api/assignment_builder/src/types/assignment.ts
- bases/rsptx/assignment_server_api/routers/instructor.py
- components/rsptx/validation/schemas.py
Fix #962 
"Allow Late Submissions": True equals `enforce_due=False`
> issue-962 Add enforce due date feature

- bases/rsptx/admin_server_api/routers/lti1p3.py
What it says...
The `context` info provided by an LMS is the ideal way to identify the course that sent the request. But it is not strictly required by the LTI protocol as part of the launch request. So I built a backup mechanism to store the RS course as a query param in the link set up in LMS. But when book links are copied, that query param won't automatically update (and can't be changed by RS). So, whenever possible, we should rely on the `context` in the request and only use the fallback when necessary.
> LTI1p3 - improve course detection for copied assignments

- bases/rsptx/admin_server_api/routers/lti1p3.py
Improves display of existing/possible links for LTI1p3, especially if LMS assignment has been renamed and no longer matches RS name.
> LTI1p3: improve display for possible matches in content selection dialog
