RunestoneInteractive/rs

- bases/rsptx/interactives/runestone/poll/poll.py
This fixes the thing that prevented `pretext` from loading `rs-substitutes.xml`.
> Put quote marks around id to keep XML happy.

- bases/rsptx/interactives/runestone/activecode/activecode.py
This, fixes, I believe, the problem I was having where code in an activecode node that also had some leading text wasn't having special XML characters escaped.
> Always escape initialcode.

- bases/rsptx/interactives/runestone/common/js/renderComponent.js
- bases/rsptx/interactives/webpack.index.js
When React requests that several components render at once, there is a webpack error relating to importing various Runestone components. Though the exact cause of the error is unclear, it is a race condition of some sort.
This PR adds a queuing system to imports. All imports requested by Runestone within 10ms of each other are queued. They are all imported together and then control is passed back to Runestone.
> React Fixes

- bases/rsptx/interactives/runestone/__init__.py
- bases/rsptx/interactives/runestone/__main__.py
I'm actually confused why this is needed. The `path` method is deprecated as of 3.11 but the description of what it does is the same as in 3.10. But with this change I can run `python -m runestone build` under both 3.10 and 3.11 while without it it explodes under 3.11.
> Fix for python 3.11

- docs/source/developing.rst
I think these are both right. I lost some time because I was following one of these and just did `poetry install` rather than `poetry install --with=dev`.
> Add --with=dev in a few more places in docs.

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/js/activecode-i18n.en.js
- bases/rsptx/interactives/runestone/activecode/js/activecode-i18n.pt-br.js
- bases/rsptx/interactives/runestone/activecode/js/activecode-i18n.sr-Cyrl.js
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
Turns out CodeMirror has an API for indenting lines which is good since that way the formatting will be consistent with what you get by hitting tab and shift-tab while editing code. So this was actually quite simple to add.
> Add "Reformat" button to activecode elements.

- bases/rsptx/interactives/package-lock.json
- bases/rsptx/interactives/package.json
- bases/rsptx/interactives/runestone/activecode/js/livecode.js
@bhoffman0 was running into problems with a new lesson that includes some file uploads when the files were not straight ASCII text because `btoa` was choking on them. This patch fixes that.
> Switch to byte-base64 to encode uploaded files.

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
The active code buttons don't fit and overflow on smaller mobile screens. 
flex-wrap: wrap; will make them wrap instead of overflow.
Suggestions for the future: shorten the text on the buttons or use icons to make them fit.
> Wrap active code buttons for mobile devices

- bases/rsptx/interactives/runestone/webgldemo/css/webglinteractive.css
Comment out css from webgl interactive that changes all scroll bars on any page using runestone.
> Remove webgl css that affects scrollbars globally

- bases/rsptx/web2py_server/applications/runestone/docs/lti.rst
I ran into a number of small gotchas that nearly made me give up integrating Runestone with Moodle. These changes attempt to clarify the instructions to match what was actually needed to make them work together properly.
> Updated Moodle LTI instructions

- components/rsptx/templates/_base.html
- components/rsptx/templates/assignment/student/assignment_block.html
- components/rsptx/templates/book/course/current_course.html
The way the code is currently the course name is added the `<ul>` floating in space, not part of any `<li>`. Also both the link and the text of the "Back to" item were missing the course name. This fixes that. I'm not sure if this is exactly what you were going for but it doesn't look broken.
> Fix floating course name.

- bases/rsptx/interactives/ptxrs-bootstrap.less
The purged code adds a font-size to the HTML element of any pretext book that makes use of runestone components.
At a bit of a loss for why it is injected into the CSS. Purging it does not appear to break any runestone components.
If it does serve a purpose, there must be a better way to achieve the goal than to change entire page's base font size. Happy to tinker with that if you can point me to what this is trying to do.
> Remove html level font-size change in rsptx .less

- bases/rsptx/web2py_server/applications/runestone/modules/db_dashboard.py
When looking at the actual student progress page for one of my current classes I noticed one of the rows getting weirdly indented.
Poking around a bit it seems that the problem is the percentages of the preceding row, each rounded to two decimal places as they are to set the widths of each segment of the progress bar, add up to 100.01 and thus overflow the enclosing div. This patch tries to fix it. I couldn't figure out a good way to test it on my local cluster without creating 27 fake students, etc. but the page still at least works.
> Try to stop the progress bars from overflowing.

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
compiler output may include <, >, etc which need to be turned into html entities, so catch the compiler output and do the substitution.
closes #21
> escape compiler text -> html

- docs/source/developing.rst
This section currently displays in the docs as a big block of text because markdown is silly and requires an extra newline to work right in this case.
Here is the github preview of the file after the change:
> Fix display of a numbered list in developing.rst

- components/rsptx/build_tools/core.py
Looks for ==== in text of pretext activecodes. If found, checks text after for strings indicating unittests.
Current string list *should* match sql/py/java/cpp unittests
> Mark autogradable questions from ptx books in DB

- bases/rsptx/interactives/runestone/common/css/user-highlights.css
I see this when I am in an Assignment page and use the dropdown menu:
where the menu content spills over. If I remove the float CSS as in this PR, it becomes:
I'm not sure if the float CSS was in there for a reason, but I couldn't identify a reason to keep it. (However in testing, I found an issue with this page on small screens that I will report separately.)
This is also me testing the waters for submitting a PR to Runestone. Is it helpful to work this way instead of just reporting the issue? Like is this too small of a thing, and I should gather together other small things to package in one PR? Differnet projects have different customs, and I want to do whatever is helpful for RA.
> minor CSS problem

- docs/source/contributing.rst
**Welcome to Runestone Documentation > Contributing to the Runestone Project : Getting Started (line 1)**
Change: Direct new contributors to the issue queue and encourage them to work on `good first issue` tasks. 
fix #398 
**Modified this line** 
If you are wondering what needs to be done, please check out our [Projects page](https://github.com/orgs/RunestoneInteractive/projects) on github.
**To:**
If you are wondering what needs to be done, please check out our[ issues queue](https://github.com/RunestoneInteractive/rs/labels/good%20first%20issue) for a good first issue or our [Projects page](https://github.com/orgs/RunestoneInteractive/projects) on github.
> Direct new contributors to issues queue

- README.rst
Issue: The ReadMe was a little confusing because new contributors were directed to two different pages, the developing section of the documentation and the contributing section of the documentation to get started,
Fix: Changed link from developing section of the documentation to contributing section of the documentation. Additionally, reminded readers to finish reading the readme before moving on.
Test: Built readme in branch and ensured proper formatting.
Fix #396
> Fix clarity in readme. issue396

- docs/source/poetry.rst
Fixed a typo that was shown as 'thr', fixed it to 'the', also changed the wording of the word whatever for something easier to understand, and added instructions about entering the repository before doing ``cd rs``, all of this was made in the file poetry.r
st
Fixes issue #403
> I fixed different typos in the poetry.rst files

- bases/rsptx/interactives/runestone/webwork/js/webwork.js
This should make it so that with MC questions, RS stores the actual value(s) of the input element(s) with MC exercises, instead of text strings associated with those input elements. 
I have not tested this at all because I don't know how I would go about doing that. Does the code look like it makes sense? If so, then the next thing to do is look at what gets saved for the exercises @Tanaquil18 listed in #373 (near the bottom of the thread at present) and see that this is indeed grabbing "values" and not strings that are unhelpful for identifying which items to select when restoring previous answers.
After this is in, I will have follow-up work in `pretext-webwork.js` to actually make use of what will now be saved. And it should (fingers crossed) put #373 to bed.
> for WeBWorK, store student_value with MC exercises

- bases/rsptx/interactives/runestone/activecode/js/acfactory.js
fix #31 
With Scratch ActiveCode allowing multiple possible languages, it might help to inform a reader what language is being interpreted. I couldn't see it anywhere.
- State present language being interpreted. 
e.g for a cpp course --> Scratch ActiveCode (C++)
- Refactor code that sets the stdin string. Now makes use of the languageNames dictionary.
> issue#31 Report the language employed by a Scratch ActiveCode Window

- bases/rsptx/web2py_server/gluon/main.py
- docker-compose.yml
- dstart
- projects/nginx_dstart_dev/Dockerfile
- projects/nginx_dstart_dev/runestone
- projects/nginx_dstart_dev/runestone.dev
- The dstart script was already present, but only started individual servers. It is hard to work with because different URLs are served by different microservices, which are served on different ports and clicking links wouldn't lead to the right address. Some individual pages require APIs or static files served from different services so cannot render properly at all.
- Add new nginx container called nginx_dstart_dev that can be used to navigate the site at localhost:8080 and redirects requests to the host machine python processes on the ports specified in the dstart script
- add option "all" to the dstart script to start all of the servers in the background
- add option "stopall" to the dstart script to stop all of the servers, as the "all" option starts them in the background so they …
> Add dev environment that removes the need to rebuild containers

- bases/rsptx/interactives/runestone/parsons/js/lineGrader.js
World's dumbest PR...
A better approach would be to only penalize incorrectly indented correct lines. But that would be a significant refactor for very little gain.
> Enforce 0 as min score for lineGrader Parsons

- bases/rsptx/interactives/package.json
- bases/rsptx/interactives/runestone/conftest.py
- bases/rsptx/interactives/runestone/fitb/dynamic_problems.rst
- bases/rsptx/interactives/runestone/fitb/fitb.py
- bases/rsptx/interactives/runestone/fitb/fitb_html_structure.html
- bases/rsptx/interactives/runestone/fitb/js/fitb-i18n.en.js
- bases/rsptx/interactives/runestone/fitb/js/fitb-utils.js
- bases/rsptx/interactives/runestone/fitb/js/fitb.js
- bases/rsptx/interactives/runestone/fitb/js/libs/aleaPRNG-1.1.js
- bases/rsptx/interactives/runestone/fitb/js/timedfitb.js
- bases/rsptx/interactives/runestone/fitb/test/_sources/index.rst
- bases/rsptx/interactives/runestone/fitb/test/test_fitb.py
- bases/rsptx/interactives/runestone/fitb/toctree.rst
- bases/rsptx/interactives/webpack.config.js
- bases/rsptx/interactives/webpack.server-index.js
I took the work the @bjones1 did in the old RunestoneComponents repository for dynamic (randomized) FITB components and reimplemented the work under the new MonoRepo. Hopefully this makes a good starting point to pick up the next step in getting this implemented.
> Randomized FITB components implemented

- bases/rsptx/interactives/package-lock.json
- bases/rsptx/interactives/package.json
- bases/rsptx/interactives/runestone/fitb/js/fitb-utils.js
- bases/rsptx/interactives/runestone/fitb/js/fitb.js
The fitb component did not deal correctly with empty feedback string. Updated the code in interactive/runestone/fitb/js/fitb.js to catch this possible error.
Also updated version on btm-expressions for some critical changes in behavior.
> FITB: fix blank feedback; update btm-expressions version

- bases/rsptx/interactives/runestone/parsons/js/parsons.js
Bug fix - currently if a Parsons line has "#distractor #tag:cSquared; depends:a,b;" only the first #tag gets removed
See demo
https://jsbin.com/fapapahewe/edit?js,console
> Strip multiple tags from parsons

- bases/rsptx/interactives/package.json
- bases/rsptx/interactives/runestone/fitb/js/fitb-utils.js
- bases/rsptx/interactives/runestone/fitb/js/fitb.js
Javascript-based testing of answers was not fully compatible with string/number testing. Non-dynamic problems with mathematics in the statement were not rendering in MathJax.
Modifications made to adjust the answer testing for the missed cases. Moved the queueing of MathJax rending out of renderDynamicContent to each reference where the html was being updated.
Also btm-expressions (npm webpack package for math objects) had some bug-fixes and improvements that need to be available for math fitb problems.
> Fitb update

- bases/rsptx/interactives/package-lock.json
- bases/rsptx/interactives/package.json
- bases/rsptx/interactives/runestone/fitb/js/fitb.js
* Add character indicators (checkmark/x-mark) to FITB feedback for correct/incorrect.
* npm version change for btm-expressions (math formula support)
* Added ability for formulas to do some automatic algebra reductions
* Automatic simplification of formulas involving constants
The authored feedback for fillin problems doubles as text for the automatically-generated solution in PreTeXt sources. That feedback does not necessarily have enough context clues to indicate if an answer was correct or not (in the case of multiple blanks), so the addition of a checkmark when correct and and "x" when incorrect should improve visual clues of correctness. The characters match what is used for multiple choice feedback.
The btm-expressions version update facilitates improved automatic simplification of …
> Updates to support FITB/math problems

- projects/jobe/files/CodeTestHelper.java
This pass through method wasn’t passing necessary args for methods that take arguments. Now it does.
> Pass args instead of null

- bases/rsptx/interactives/runestone/parsons/js/parsons.js
PTX generates the language attribute as `cpp`. The RS Parsons JS is looking for `c++`. This makes RS accept either string as being c++ code.
> Add cpp as a pretty language for parsons

- bases/rsptx/interactives/runestone/parsons/js/parsons.js
Typo in Parsons code prevents it from waiting for MathJax to format. Thus you can get cut off content as proper width was not known:
This fixes the issue:
> Fix bug that prevents parsons from waiting for mathjax formatting

- README.rst
There was a second set of backticks in one of the links that was somehow missed last week when other links were fixed.
> Fix link to Discord on README.rst

- bases/rsptx/web2py_server/applications/runestone/views/peer/dashboard.html
- components/rsptx/db/crud.py
This PR contains the following edits:
- `get_peer_votes()`: This function, in `crud.py`, has been modified to only fetch every student's latest votes for creating the graphs on the PI Review Page. Previously, the function would fetch every vote, leading to duplicate entries in the graphs.
- PI instructor dashboard UI fixes: Barb wanted me to move around the chat buttons so that "In-person Chat" is situated before "Text Chat" and the feedback div is moved beneath all the buttons.
> Fix: get_peer_votes function to fetch every student's latest votes only

- bases/rsptx/interactives/runestone/tabbedStuff/css/tabbedstuff.css
Fix for issue reported here:
https://groups.google.com/g/pretext-support/c/6Vp3lbOLYw0
It appears that when there was more than one row of tabs, later rows floats could "hang" on the border added to the <a> in the active one.
> Fix floating tabs hanging on active one

- bases/rsptx/interactives/ptxrs-bootstrap.less
We refactored a few of the CSS variable names defined in new themes. This updates the RS variables that attempt to point at those to use the new names.
Should be safe to deploy whenever.
> Update var names that are linking to PreTeXt defined variables

- bases/rsptx/interactives/runestone/activecode/js/activecode_sql.js
This makes sql-wasm and DB files load correctly for static HTML builds with PreTeXt. Tested with local copy of sample-book.
I don't *think* this should affect RST based builds negatively. I think it might help them... `/_static` is almost never going to be the right way to start the URL.
Should be able close these two:
https://github.com/RunestoneInteractive/rs/issues/584
https://github.com/RunestoneInteractive/rs/issues/351
> Fix URLs for SQL Activecode PreTeXt books built for static HTML

- bases/rsptx/web2py_server/applications/runestone/controllers/dashboard.py
- bases/rsptx/web2py_server/applications/runestone/views/dashboard/index.html
Fixes the links shown in image below for PTX books.
I don't love the solution (borrows code from higherup in index.html). It seems like it could get messy fast to have the template logic doing lots of deciding what platform it is working with. Should both get refactored so that the controller (or the `get_course_url` function does the work of handling PTX/RS?
> Fix dashboard/student-progress exercise analytics links in PTX

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/css/activecode.less
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
- bases/rsptx/interactives/runestone/activecode/js/activecode_sql.js
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
Changes:
- Styling for unit test and code coach for python
- Styling for SQL unit test and error message
- Removes "dirty" style from code editor on run
- No display of error box if empty
> CSS darkmode adjustments for activecode

- bases/rsptx/interactives/runestone/parsons/js/dagGrader.js
- bases/rsptx/interactives/runestone/parsons/js/lineGrader.js
- Both DAG and Line grader now skip deep analysis of indentation if problem is marked to not require it.
- Fixes a bug in line grader.
- Changes DAG grader to look at each block's indentation instead of comparing each line to expected indentation for the block it is in (requiring same indent for all lines).
> Parsons indentation marking fixes

- bases/rsptx/interactives/runestone/parsons/css/parsons.css
- bases/rsptx/interactives/runestone/parsons/js/parsons.js
Improves block sizing for Parsons problems. New pretext styling upset some of the delicate magic.
This reduces some of the assumptions for the `sourceRegion` width. Instead of starting at 425px max, the max possible width is calculated based on what is actually available. There is also no longer a min width of 300, so in a narrow view, you can still end up with side by side presentation if the content is reflowable.
> Better block sizing for parsons problems

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
Currently livecodes ignore any changes to editable datafiles.
`el.textContent` only returns the initial contents of the text area. `el.value` is required to get to the current contents.
> Allow livecodes to read updated contents of editable datafiles

- docs/source/javascript_feature.rst
Capturing the gotcha's that I had to overcome when trying this for the first time.
Note that the way the CLI specifies stringparams is different in 2.0.
> add some details to the javascript development instructions

- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
This addresses the contrast errors for keywords in activecode in light mode.
A PR to pretext to have their keywords match this color will follow.
> darken pretext keyword color to fix contrast error

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
This addresses the penultimate issue related to active code accessibility: the use of `@lang` in a outerDiv to help determine the value of the programming langue for the textarea.  Switched to `@data-lang` and tested against the sample book.
> use data-lang attribute instead of lang for createEditor function

- bases/rsptx/web2py_server/applications/runestone/static/js/admin.js
Issue raised by Debbie in Discord:
https://discord.com/channels/1013815439161315348/1013815440000159847/1348362626748387338
Grading page needs to use assignment date to call `getTimezoneOffest` and not `now`
> Grading page due date DST fix

- bases/rsptx/interactives/runestone/parsons/css/parsons.css
- bases/rsptx/interactives/runestone/parsons/js/parsons.js
Allows blank lines to appear in the middle of a Parsons block.
Instead of trimming all blank lines, the JS now prunes at most one blank line from start and end.
> Allow blank lines in the middle of Parsons blocks

- bases/rsptx/interactives/runestone/parsons/js/dagGrader.js
The DAG grader currently checks indentation even for distractors - which are always marked wrong.
This omits them from the indentation check
> Bugfix for distractors in DAG grading - ignore for indentation check

- bases/rsptx/interactives/runestone/dragndrop/css/dragndrop.css
- bases/rsptx/interactives/runestone/dragndrop/js/dragndrop.js
Adds the method adjustDragDropWidths to set widths (within constraints) dynamically. Integrates calls to this method after rendering, resetting, and dragging/dropping items. It also addresses the minimum height of the zones that do not reset after the reset button is pressed.
> Flexible drag and drop widths

- bases/rsptx/interactives/runestone/datafile/css/datafile.css
Datafiles currently get 30ems of height even if they are only 1-2 lines. Better as max-height to constrain long files but not add whitespace to short ones.
Only affects non-editable datafile as editable get row/cols sizing via textarea.
> Datafile height to max-height

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
Two cleanups. 
First  commit changes max & min size on code mirrors. Sets a min to prevent resizing so small you can no longer grab resize handle. Max is set to always fit on screen with run button. Goal is that for long codemirrors, users scroll the code mirror and never have to scroll window while editing.
Second commit refactors the locked code decoration. Apparently inserting the gutter markers is rather inefficient. On exercise pages with 10+ exercises each with 20ish lines of locked code I was seeing 15+ second load times for code mirrors. This reduces the number of lock markers drawn by showing a line to indicate locked region (which I think looks better anyway). It also avoids drawing the lock markers in the initial editor creation - they snap in after a short delay. Finally, it …
> Activecode locked regions improvements

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
When an activecode is initially hidden (e.g. in a tab), Codemirror does not render the lines. Thus the initial existing height calculation is wrong and line decorations (locked regions) are not applied correctly. Commit 1 addresses this.
Commit 2 gets rid of the current overlap between vscrollbar and resize handle:
> Better tabbed activecode handling

- bases/rsptx/web2py_server/applications/runestone/views/designer/index.html
Maybe when creating a course, the introducTory level should not suggest just CS1 and CS2?
> More generic "introductory" course level

- bases/rsptx/interactives/runestone/activecode/css/activecode.css
- bases/rsptx/interactives/runestone/activecode/css/activecode.less
- bases/rsptx/interactives/runestone/activecode/css/codemirror-dark.less
- bases/rsptx/interactives/runestone/activecode/js/activecode.js
Adds handling for highlight-lines attribute that can be specified in PreTeXt markup for programs to activecodes.
The highlighting is intentionally only shown when when the history slider is at the position 1 to avoid highlighting the wrong lines in versions students have edited.
Depends on pretext PR https://github.com/PreTeXtBook/pretext/pull/2473 to function, but should be safe to merge without the partner PR.
> Handle highlight lines specified in PTX markup

- bases/rsptx/book_server_api/routers/rslogging.py
- bases/rsptx/interactives/runestone/datafile/__init__.py
- components/rsptx/db/crud.py
Bug fix for the recent PR.
Debbie Yuster reported a bug with cross book lookup of datafiles. I think the issue is datafiles that are in the DB without a filename in the source_code table. The migration from previous PR took care of old builds, but I think rebuilds were still missing filenames.
This has fixes at both ends:
*Makes sure the RST datafile build script adds filenames to the source_code table
*Modifies the crud.py `fetch_source_code` function to, when a datafile is requested by filename, match the filename against either the filename OR the acid.
Should not need a book rebuild for `fetch_source_code` to fix issue Debbie reported. But first fix will make sure everything is in DB correctly on build.
> Bugfix for RST datafiles lookups

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
The -fsanitize compiler flag generates code that requires a large shadow block of memory which exceeds the Jobe  default limit. This detects attempts to use fsanitize and tells Jobe to set a very high memory limit.
> Activecode - set large memorylimit if code tries to use fsanitize

- bases/rsptx/interactives/runestone/hparsons/css/hparsons.css
- bases/rsptx/interactives/runestone/hparsons/js/BlockFeedback.js
Found some style rules that were limiting the growth of hparsons.
Pulled them out so that "wide" themes.
Books using RST will not be affected. In PreTeXt books using deprecated style="wide", hparsons get a bit wider. In modern wide themes, hparsons will not be able grow to width controlled by theme.
> HParsons style cleanup - remove hardcoded max-widths

- bases/rsptx/interactives/runestone/hparsons/js/hparsons.js
This patch extends the Runestone hparsons component to support math-mode horizontal Parsons problems.
> Add math-mode support for horizontal Parsons problems

- bases/rsptx/interactives/ptxrs-bootstrap.less
- bases/rsptx/interactives/runestone/common/css/runestone-custom-sphinx-bootstrap.css
- bases/rsptx/interactives/runestone/mchoice/css/mchoice.css
Legends (e.g. `Chose one` message for multiplechocie) currently always have dark text and are unreadable in dark mode. This makes them controlled by an existing CSS variable.
Also adds some margin to the top of a class that will appear in https://github.com/PreTeXtBook/pretext/pull/2506 to fix a lack of space above the legend that will otherwise appear with that PR.
> Color/spacing fixes for fieldset/legend in exercises

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
Fix for livecodes with no compiler args failing to run.
> Check compilerargs in livecode before coercion

- bases/rsptx/interactives/runestone/video/css/video.css
Sean reported a CSS bug in APEX. Turns out it is this rule from video.css:
```
.exercises {
background-color: #f0ffff;
}
```
I can't see where it is used, so I removed it. If it is needed, we need to restrict its scope.
> Remove .exercises from video.css

- components/rsptx/build_tools/core.py
when building a pretext book, I see this warning:
```
/Users/jason/rs/components/rsptx/build_tools/core.py:692: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
if el and "practice" in el.attrib:
```
The fix is easy enough, just use `is not None` test.
> use is not None test to prevent futurewarning

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
If PTX puts a list of files into compile-also, RS is currently not breaking that list up into individual files. This fixes that.
> Bugfix for compileAlso getting list of files

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
- bases/rsptx/interactives/runestone/activecode/js/activecode_js.js
- bases/rsptx/interactives/runestone/activecode/js/activecode_sql.js
- bases/rsptx/interactives/runestone/activecode/js/livecode.js
This PR fixes some cases where `aria-live` tags were missing for activecode results. Notably:
- Codecoach outputs now have proper tags (bb3d3924f0144085ffcf743efcf6d82473f935b2)
- Javascript errors are properly tagged (5503d7ae5e26bc3f7359553eac883713a374d4fa)
- Languages that use JOBE have their errors properly tagged (a5b1ca96e11165e7786ad85cea5e2b25b093556d)
- SQL results are properly tagged (7e2db26b770cd74cf71d9414783e883299dacc27)
These issues were caused by the fact that originally the tags were only added in `activecode.js`, and not the other files that can generate their own error/output divs (see diff for details on where this happens).
This PR resolves RunestoneInteractive/rs#635.
> Fix aria-live tags for activecode error/stdout

- bases/rsptx/interactives/runestone/common/project_template/_templates/plugin_layouts/sphinx_bootstrap/layout.html
- bases/rsptx/web2py_server/applications/runestone/views/layout.html
This PR addresses the issue that the "back to top" links in the application only scroll to the top of the page, and don't reset keyboard focus. This means if a user were to hit tab after clicking "back to top", they'd be sent back to the bottom of the page instead of the first focusable element as intended.
Changes:
- For RST-based books, we include a "dummy" div at the top of the page that the javascript can set focus to. An alternative would be to just have it focus the runestone logo (which felt slightly less portable to me), but I can have it work that way if you'd prefer.
- For the instructor page (and other pages served by that layout), we return focus to the existing "skip to content" element (which is first in the focus order)
> Back to top keyboard focus fix

- components/rsptx/templates/book/index.html
- components/rsptx/templates/staticAssets/index.css
Currently, the focus indicators on the book titles in the library are broken:
Instead of a proper focus indicator surrounding the title link, there is (on firefox) a small dot in the corner. On some other browsers, there was no focus indicator at all.
This PR fixes the focus indicator (so that it surrounds the whole link), and also causes the color change triggered by a mouse hover to also be triggered by keyboard focus (similar to how buttons behave):
> Book Index Focus Fix

- projects/jobe/Dockerfile
the catch2 package in ubuntu24 is not version 2.x it is version 3.x which is NOT backward compatible. Solution: fetch the latest version of 2.x from github and use that instead.
> use -real- catch2 not catch3 masquerading as 2.x

- bases/rsptx/interactives/runestone/activecode/js/acfactory.js
- bases/rsptx/interactives/runestone/common/project_template/_templates/plugin_layouts/sphinx_bootstrap/layout.html
- bases/rsptx/web2py_server/applications/runestone/views/layout.html
When the activecode modal is closed, focus is intended to return to the pencil icon (that was used to open the modal originally). There is currently code for this:
```js
let closeBtn = document.querySelector(".ac-modal-header button.close");
closeBtn.addEventListener("click", function () {
let popUp = document.getElementById("ac_modal_" + divid);
popUp.style.display = "none";
document.querySelector("button.activecode-toggle").focus();
});
```
However, it errors since `document.querySelector("button.activecode-toggle")` fails to find any elements:
I'm guessing this is some sort of regression where the HTML was changed after this feature was implemented.
This PR fixes the selector/html so that the functionality works properly again.
> Fix focus on activecode modal close

- bases/rsptx/rsmanage/core.py
If a course is created via `rsmanage --addcourse` from a basecourse/book before that book has been built, then the needed attributes don't exist yet and are not copied over. This PR adds a check to prevent a user from accidentally creating a course too soon.
> Check that the basecourse/book has been built before creating a course from it

- bases/rsptx/interactives/runestone/mchoice/css/mchoice.css
- bases/rsptx/interactives/runestone/mchoice/js/mchoice.js
For multiple choice questions:
the HTML currently has a `<legend>` element with "choose one" or "choose multiple", and the actual question content is outside of this element:
```html
<div id="question1_1" class="runestone-component-ready">
<p>What programming language does this site help you to learn?</p>
<form id="question1_1_form" method="get" action="" onsubmit="return false;">
<fieldset>
<label>
<p><input type="radio" name="group1" value="0" id="question1_1_opt_0">A. Python</p>
</label>
<br>
... (other answers elided for brevity)
<legend>Choose one</legend>
</fieldset>
<button class="btn btn-success" name="do answer" type="button">Check Me</button>
</form>
<br>
<div id="question1_1_feedback" aria-live="polite" role="status"></div>
<p class="runestone_caption">Activity: 2.1.1 Multiple …
```
> Fix multiple choice question accessibility issue

- bases/rsptx/admin_server_api/routers/lti1p3.py
- components/rsptx/db/crud/__init__.py
- components/rsptx/db/crud/lti.py
- components/rsptx/lti1p3/pylti1p3/service_connector.py
- components/rsptx/templates/admin/lti1p3/pick_links.html
- components/rsptx/templates/admin/lti1p3/rs_login.html
Allows the LTI1p3 content selection workflow to function without access to 3rd party cookies.
If cookies are totally blocked (Epihpany, Safari???) a new window is opened and workflow happens there. It ends in an orphaned page that loads the content, which is a bit awkward, but that is an artifact of LMS handling.
If existing cookies are blocked but the iframe is allowed to make new ones (firefox with enhanced security), the user can provide their RS credentials in the iframe and then continue the content selection as normal.
> LTI1p3 - handle instructor content selection without 3rd party cookies

- projects/rsmanage/pyproject.toml
without this, rsmanage errors out importing imghdr (I -think- this is the correct fix, but I'm not sure I completely understand poetry).
> add standard-imghdr

- bases/rsptx/interactives/runestone/activecode/js/activecode.js
Just a small tweak to activecode.js to allow a book to change the indentation unit in CodeMirror using a CSS variable, e.g.
```css
:root {
--code-editor-indentation: 2;
}
```
Defaults to the old value of 4 if the variable is not set.
Tested it in my local docker cluster with and without that variable defined in the CSS.
> Enable changing CodeMirror indentation unit.

- bases/rsptx/admin_server_api/routers/lti1p3.py
- components/rsptx/lti1p3/pylti1p3/deep_link_resource.py
This sends RS assignment duedate to LMS when you use LTI to create LMS assignments from RS ones.
After that point LMS is ground truth on duedates - they are only synced from LMS --> RS.
> LTI1p3: sync RS date to LMS on assignment initial linking

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercisesList/ExerciseSuccessDialog.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ExercisePreview/ExercisePreview.tsx
- bases/rsptx/interactives/runestone/activecode/css/activecode.css
Fix #897. In exercise preview, remove unnecessary scrolls, leave only one. Fix non-clickable page bug after creating an exercise
> Fix issue 897 - New Assignment Builder: too many scrollbars

- bases/rsptx/admin_server_api/routers/lti1p3.py
Addresses https://github.com/RunestoneInteractive/rs/issues/913
Grabs the cookie returned from the `web2py_login` route that is called from admin server and adds it to the response that is returned to the users browser.
> LTI1p3 fix web2py login for launch via LTI links

- bases/rsptx/admin_server_api/routers/lti1p3.py
- components/rsptx/lti1p3/pylti1p3/cookies_allowed_check.py
- components/rsptx/lti1p3/pylti1p3/message_launch.py
- components/rsptx/lti1p3/pylti1p3/oidc_login.py
Three things to help re: 3rd party cookie issues:
* When LTI1p3 sets w2py session cookie make it always secure/samesite none. LTI1p3 won't function without https anyway.
* If an LTI redirect attempt is missing the session cookie, but has a valid state token in request, don't treat as error
* Improve messaging re: blocked cookies
> LTI1p3 cookie improvements

- bases/rsptx/web2py_server/applications/runestone/static/js/admin.js
Fix for https://github.com/RunestoneInteractive/rs/issues/970
> Fix issue 970 - confusing Push Grades to LTI message

- components/rsptx/lti1p3/core.py
I was able to recreate what I think is the issue with syncing grades.
This prevents one failed update from stopping a whole batch. It should go a long ways towards a fix. It could fix the entire issue if the errors all do in fact come from grade updates that do not make sense (sending a 0 score for an instructor).
If there are reasons why "real" updates are failing, we will be better able to diagnose those with this in place.
> LTI1p3: Handle possible grade sync exceptions on per score basis

- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/AssignmentBuilder.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/edit/AssignmentEdit.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/AssignmentExercisesList/AssignmentExercisesTable.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/ChooseExercises/ChooseExercisesHeader.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SmartSearchExercises.module.css
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/exercises/components/SearchExercises/SmartSearchExercises.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/components/routes/AssignmentBuilder/components/reading/AssignmentReadingsTable.tsx
- bases/rsptx/assignment_server_api/assignment_builder/src/utils/exercise.ts
- Removed the breadcrumb in exercise editing to free up more space (it wasn’t useful anyway; site navigation needs a redesign).
- Added a switch in Browse Exercises to show only exercises from the book.
- Added the ability to sort exercises by source.
- Fixed a visual bug in the multiselect for choosing exercise types (Browse Exercises, Search Exercises).
fix #869
> issue-869 Enhance exercise filtering in ChooseExercises with a toggle switch and improved layout

- bases/rsptx/interactives/runestone/activecode/js/livecode.js
The updated whitespace trimming results in student answers that are missing a trailing newline always being wrong.
PreTeXt always generates a newline at the end of the `<output>` block of an `<iotest>`. I don't necessarily love that, but it is consistent with other PTX behavior when processing code like blocks. So in the screenshot below, the expected answer is:
```
4 5
```
With a trailing newline.
The provided answer is:
```
4 5
```
Without a newline. 
The rendered output gives no indication that there is an issue. Even wrapping the outputs in `<pre>` tags won't make the issue visible. 
@skiadas This will mean students never get answers wrong for missing or extra trailing newlines. But I think that is much better than the current behavior. Do you see a reason to ever mark those wrong? If …
> Livecode: better handling of trailing newlines and pre formatted output boxes
